stages:
  - build-app
  - build-image

build app:
  stage: build-app
  image: node:16
  before_script:
    - npm i
    - npm i -g pm2
  script:
    - npm i
    - npm run build
    # - npm run start:prod
    # - pm2 delete backend
    - pm2 start dist/main.js --name "backend" 
    # - pm2 start dist/main.js --name <application_name>
    - pm2 save
    - echo "done"

build iamge:
  stage: build-image
  image: docker:20.10.17
  services:
    - docker:20.10.17-dind
  variables:
    IMAGE_NAME: sepehr310/cicd
    IMAGE_TAG: nest-00-1b
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
   - docker login -u $dockerUsername -p $dockerPassword
  script:
    - docker build  -t $IMAGE_NAME .
    - docker push $IMAGE_NAME .
 
