version: '3.8'

services:
    server:
        container_name: nest-devops
        image: nest-devops:latest
        build:
            context: .
            target: development
            dockerfile: ./dockerfile
        command: npm run start:dev
        ports:
            - 3000:3000
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    nginx:
        build: ./nginx
        ports:
           - '80:80'
        depends_on:
           - server

networks:
    nesjs-network:

